const providersData = [
  {
    "id": "prov_1769213763329",
    "company-name": "New Provider",
    "category": "accounting",
    "description": "",
    "location": "",
    "rating": 5,
    "reviews": 0
  },
  {
    "id": "prov_1769212122806",
    "company-name": "New Provider",
    "category": "legal",
    "description": "reftgrfht",
    "location": "waders",
    "rating": "5",
    "reviews": "0",
    "email": "",
    "phone": "",
    "website": "",
    "specialties": ""
  },
  {
    "id": "prov_1768762600064",
    "company-name": "Test3",
    "category": "accounting",
    "description": "wifi",
    "location": "ew",
    "rating": "5",
    "reviews": "0",
    "email": "",
    "phone": "",
    "website": "",
    "specialties": ""
  },
  {
    "company-name": "Startosphere Sample",
    "category": "accounting",
    "description": "This is a sample provider entry.",
    "location": "London, UK",
    "rating": "5.0",
    "reviews": "1",
    "email": "hello@startosphere.com",
    "phone": "0800 123 456",
    "website": "https://startosphere.com",
    "specialties": "Startup Finance, Tax",
    "id": "sample_1"
  },
  {
    "company-name": "Test2",
    "category": "accounting",
    "description": "Test",
    "location": "London",
    "years-experience": "5",
    "contact-name": "RK",
    "email": "Raihan.lakers@gmail.com",
    "phone": "02937",
    "website": "",
    "services": "Test",
    "specialties": "wkuhe",
    "stage-pre-seed": "on",
    "clients-served": "",
    "additional-info": "wqeflirj",
    "id": "imp_s7nq51z6b",
    "rating": "5",
    "reviews": "0"
  },
  {
    "company-name": "MacBook",
    "category": "hr",
    "description": "Hiring company that welfnwlnlwenoiwefwoifjweoifhodnwjbvwkvjbwekjbwekbwewbekwejbewkjbewlewlfjewldjwelvwelvewvlewvnhewlvwelvkbwelvweblvwkbvlejbvew",
    "location": "Edinburgh, UIK",
    "years-experience": "208",
    "contact-name": "wefjnbwr ewkfjnrw",
    "email": "erjfv@gmail.com",
    "phone": "07939987254",
    "website": "",
    "services": "Hiring, training, wewfloneqfinrwgwejfnwelkfjn",
    "specialties": "Hiring, HR, Testing",
    "stage-series-a": "on",
    "clients-served": "294",
    "additional-info": "Because we're sick",
    "id": "imp_3klb5m7js"
  },
  {
    "company-name": "MacBookshb",
    "category": "hr",
    "description": "Hiring company that welfnwlnlwenoiwefwoifjweoifhodnwjbvwkvjbwekjbwekbwewbekwejbewkjbewlewlfjewldjwelvwelvewvlewvnhewlvwelvkbwelvweblvwkbvlejbvew",
    "location": "Edinburgh, UIK",
    "years-experience": "208",
    "contact-name": "wefjnbwr ewkfjnrw",
    "email": "erjfv@gmail.com",
    "phone": "07939987254",
    "website": "",
    "services": "Hiring, training, wewfloneqfinrwgwejfnwelkfjn",
    "specialties": "Hiring, HR, Testing",
    "stage-series-a": "on",
    "clients-served": "294",
    "additional-info": "Because we're sick",
    "id": "imp_n1yo2o7as"
  },
  {
    "company-name": "gyhkj",
    "logo": {},
    "category": "hr",
    "description": "jhk",
    "location": "jkl",
    "years-experience": "8",
    "contact-name": "ghj",
    "email": "hkjn@gmail.com",
    "phone": "789",
    "website": "",
    "services": "98uoijk",
    "specialties": "",
    "clients-served": "",
    "additional-info": "",
    "id": "imp_m48xxueoz"
  },
  {
    "company-name": "qwer",
    "logo": {},
    "category": "fundraising",
    "description": "qwde",
    "location": "234",
    "years-experience": "34",
    "contact-name": "as",
    "email": "dew@gmail.com",
    "phone": "1234",
    "website": "",
    "services": "sad",
    "specialties": "",
    "clients-served": "",
    "additional-info": "",
    "id": "imp_0o0lst18r"
  }
];